apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  type: nodePort
  selector:
    app: register-app

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30009
